### ISSUE TITLE
Player shops selling spawners is broken

### ISSUE THREAD

**Issue by apmarsenault** [firestarter/bulletin#23]
As per Hailey

**Comment by apmarsenault** [comment]
Just says "Shop is out of stock." when items are in there to be sold.

**Comment by nkomarn** [comment]
This has been fixed as of https://github.com/firestarter/plugins/commit/bfb4215a32d6c3553dac64a108332883054116db.

**Comment by nkomarn** [comment]
> This has been fixed as of [firestarter/plugins@bfb4215](https://github.com/firestarter/plugins/commit/bfb4215a32d6c3553dac64a108332883054116db).

I lied, this appears to still be busted in production despite working flawlessly on the development server.

---
Additionally, tab completing `/buy` brings up an entry called " Spawner" (with a space in front). There are also messages in the server's console on startup which say "Skipping BlockEntity with id."

I believe this is due to blank spawners actually being "player" entity spawners on the server in the past. I'll have to create a converter for these legacy spawners since they cause issues with the shop system.

![image](https://github.com/firestarter/bulletin/assets/22900187/d8198fe1-6d3a-4711-a1c2-632908ad26b6)
![image](https://github.com/firestarter/bulletin/assets/22900187/501df886-ed00-4b3b-abce-7ca8fd5ad083)

**Comment by nkomarn** [comment]
> This has been fixed as of [firestarter/plugins@bfb4215](https://github.com/firestarter/plugins/commit/bfb4215a32d6c3553dac64a108332883054116db).

I lied, this appears to still be busted in production despite working flawlessly on the development server.

Additionally, tab completing `/buy` currently brings up an entry called " Spawner" (with a space in front). This is likely due to the change in entity name parsing; reverting to the old behavior will likely resolve this issue.

---
Either way, the necessary changes have been made in [this commit](https://github.com/firestarter/plugins/commit/bd8f6c2d1ab426c142583ff352a2789c4d8ab9ec) and require testing on production.
